@echo off

REM SET THE LOGFILE PATH AND SET THE NAME OF THE SERVICE THAT NEEDS TO RESTART
set LOGFILE=C:\logfile.txt
set SERVICE=XboxGipSvc

REM CHECKING THE STATUS OF THE SERVICE
echo CHEKING THE STATUS OF THE SERVICE "%SERVICE%" >> %LOGFILE%
sc query "%SERVICE%" | find "RUNNING"

REM CHECKING IF THE SERVICE IS RUNNING. IF THE SERVICE IS RUNNING STOP IT AND WRITE THAT IN THE LOGFILE
REM IF THE SERVICE IS NOT RUNNING NO NEED TO STOP IT, WRITE DOWN IN THE LOGFILE
if "%ERRORLEVEL%" == "0" (
    echo %TIME% %DATE% THE SERVICE "%SERVICE%" is running Attempting to stop it>> %LOGFILE%
    net stop "%SERVICE%" >> %LOGFILE% 2>&1
) else (
    echo %DATE% %TIME% - The service "%SERVICE%" is not running. No need to stop it. >> %LOGFILE%
)

REM START THE SERVICE AND WRITE THAT IN THE LOGFILE

echo %DATE% %TIME% STARTING THE SERVICE "%SERVICE%" >> %LOGFILE%
net start "%SERVICE%" >> %LOGFILE% 2>&1

echo %DATE% %TIME% - Service restart completed. >> %LOGFILE%
